workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
variables:
  # these containers are built manually and tagged/pushed so they can be used here
  RPM_CONTAINER_TAG: "2023-02-13"
  RPM_CONTAINER_NAME: "rippled-rpm-builder"
  RPM_CONTAINER_FULLNAME: "${RPM_CONTAINER_NAME}:${RPM_CONTAINER_TAG}"
  DPKG_CONTAINER_TAG: "2023-07-31"
  DPKG_CONTAINER_NAME: "rippleci/rippled-dpkg-builder"
  DPKG_CONTAINER_FULLNAME: "${DPKG_CONTAINER_NAME}:${DPKG_CONTAINER_TAG}"
  ARTIFACTORY_HOST: "artifactory.ops.ripple.com"
  ARTIFACTORY_HUB: "${ARTIFACTORY_HOST}:6555"
  GIT_SIGN_PUBKEYS_URL: "https://gitlab.ops.ripple.com/xrpledger/rippled-packages/snippets/49/raw"
  PUBLIC_REPO_ROOT: "https://repos.ripple.com/repos"
  RIPPLED_BRANCH: "develop"

.dind_template: &dind_param
  before_script:
    - . ./Builds/containers/gitlab-ci/docker_alpine_setup.sh
  variables:
    docker_driver: overlay2
    DOCKER_TLS_CERTDIR: ""
  image:
    name: artifactory.ops.ripple.com/docker:latest
  services:
    # workaround for TLS issues - consider going back
    # back to unversioned `dind` when issues are resolved
    - name: artifactory.ops.ripple.com/docker:stable-dind
      alias: docker
  tags:
    - 4xlarge

stages:
  - build_packages

dpkg_build:
  timeout: "1h 30m"
  stage: build_packages
  image: rippleci/rippled-dpkg-builder:2023-07-31
  tags:
    - 4xlarge
  artifacts:
    paths:
      - build/dpkg/packages/
  script:
    - echo "RIPPLED_BRANCH $RIPPLED_BRANCH"
    - export PKG_OUTDIR=pkgs
    - git clone --depth=1 --branch $RIPPLED_BRANCH https://github.com/legleux/rippled.git
    - cp packaging/dpkg/build_dpkg.sh . && ./build_dpkg.sh
